rewardStyle/YPImagePicker

Example/ExampleViewController.swift
Source/Configuration/YPImagePickerConfiguration.swift
Source/Pages/Gallery/Album/YPAlbumsManager.swift

This will allow overriding the default `PHFetchOptions` used for fetching albums like this:
```
let albumFetchOptions = PHFetchOptions()
albumFetchOptions.sortDescriptors = [NSSortDescriptor(key: "title", ascending: true)]
config.library.albumFetchOptions = albumFetchOptions
```
| Scenario | Before      | After |
|----- | ----------- | ----------- |
| Album view sorted by title | ![Simulator Screen Shot - iPhone 13 mini - 2023-02-16 at 10 13 50](https://user-images.githubusercontent.com/122308456/219443469-3a91a9ef-101e-4a98-9997-2e0f5f2de44a.png) | ![Simulator Screen Shot - iPhone 13 mini - 2023-02-16 at 10 14 16](https://user-images.githubusercontent.com/122308456/219443544-889bc2cc-6adc-4c7d-81ef-5bb2d6a073ff.png) |
This change is needed to resolve [this …

feature: Allow passing in PHFetchOptions for albums and smart albums

---

Example/ExampleViewController.swift
Source/Configuration/YPColors.swift
Source/Configuration/YPFonts.swift
Source/Configuration/YPImagePickerConfiguration.swift
Source/Pages/Gallery/Album/YPAlbumVC.swift

Using the `useAlbumSections` flag will split the albums view into three sections: "Recents & Favorites", "user albums" and "smart albums", with overridable section titles.
| Scenario |  | |
|----- | ----------- | -- |
| `config.library.useAlbumSections = true`, `config.library.smartAlbumsSectionTitle = "Media types"`, `config.library.userAlbumsSectionTitle = "My albums"` | ![Simulator Screen Shot - iPhone 13 mini - 2023-02-17 at 09 49 29](https://user-images.githubusercontent.com/122308456/219702627-1e3d767e-610c-4e40-a4d8-5235210e9d6b.png) | ![Simulator Screen Shot - iPhone 13 mini - 2023-02-17 at 09 49 32](https://user-images.githubusercontent.com/122308456/219702660-2e97a0fa-fc39-4143-88bd-72b123bae6cd.png) | 
| `config.library.useAlbumSections = false` | ![Simulator Screen Shot - …

feature: Allow turning on "album sections", instagram style

---

Source/Pages/Gallery/YPLibraryVC.swift
Source/Pages/Gallery/YPLibraryView.swift
Source/YPPickerVC.swift

When the showsLibraryButtonInTitle config value was set to false, we still incorrectly set the picker view title to the old "button" style.
| Scenario | Before      | After |
|----- | ----------- | ----------- |
| Album selected, showsLibraryButtonInTitle = false |  ![Simulator Screen Shot - iPhone 13 mini - 2023-04-06 at 12 40 16](https://user-images.githubusercontent.com/122308456/230442408-68738f47-35fd-44a0-b3aa-9b91310c272b.png) | ![Simulator Screen Shot - iPhone 13 mini - 2023-04-06 at 12 37 52](https://user-images.githubusercontent.com/122308456/230442087-3496cb84-1a53-4fca-8909-d1cefb653079.png) |
| Album selected, showsLibraryButtonInTitle = true (default functionality) | ![Simulator Screen Shot - iPhone 13 mini - 2023-04-06 at 12 40 …

fix: When the picker title is overridden, set the album title correctly

---

Source/Pages/Gallery/LibraryMediaManager.swift

We had already made a change earlier to _not_ use AVAssetExportPresetPassthrough for slomo videos here: https://github.com/rewardStyle/YPImagePicker/pull/9, but there was still a case where the user could end up with that preset if they didn't trim, crop or rotate the video but muted it. 
This change will force using `YPConfig.video.compression` in that case (which defaults to `AVAssetExportPresetHighestQuality`)

fix: Fix slomo videos potentially breaking when muting them

---

Source/Pages/Gallery/YPLibraryVC.swift

The problem was that a few methods are expecting a cropRect to exist, so we shouldn't _not_ set it. We're already preventing the user from zooming/panning on the YPAssetZoomableView so this should be fine.

fix: Prevent a crash when allowZoomToCrop = false

---

Source/Filters/Video/YPVideoFiltersVC.swift
Source/Pages/Gallery/YPAssetZoomableView.swift

The problem was that if allowZoomToCrop was set to false, we didn't force the aspect ratio to the minimum allowed aspect ratio.
Also: Make the cover selector images respect the video aspect ratio

fix: Always enforce video asset cropping to min asset ratios

---

Source/Configuration/YPImagePickerConfiguration.swift
Source/Pages/Gallery/BottomPager/YPBottomPagerView.swift
Source/Pages/Gallery/YPLibraryVC+CollectionView.swift
Source/YPPickerVC.swift

Add config to disable max selected items warning
Remove back bar from bottom of library view when selecting single item to be more consistent with multiple selection that doesn't have the bar

Image selection limit warning

---

Source/Configuration/YPImagePickerConfiguration.swift
Source/Pages/Gallery/LibraryMediaManager.swift
Source/Pages/Gallery/YPLibraryVC+CollectionView.swift
Source/Pages/Gallery/YPLibraryVC.swift

This PR works off of https://github.com/rewardStyle/YPImagePicker/pull/26 as a starting point which adds new functionality to select both videos and images from the library. This PR adds a new property `allowPhotoAndVideoSelection` on `YPConfigLibrary` which can be toggled true/false from the client. When `allowPhotoAndVideoSelection` is set to true the client will be able to make mixed selection from the library.

feat: Add Support For Mixed Photo + Video Library Selection [CC-495]

---

Source/Filters/Trim/YPTimeStampScrollView.swift
Source/Filters/Trim/YPTimeStampTrimmerView.swift

Decreases the trimmer timestamp range interval for videos 30 seconds and over to render a timestamp dot every 5 seconds instead of every 10 seconds. This allows the UI to show that there is overflow indicating that a user can scroll the video clip in the video trimmer.

fix: [CC-917] Decrease Trimmer Timestamp Interval To Show Overflow

---

Source/Configuration/YPImagePickerConfiguration.swift
Source/Filters/Photo/YPCoverImageView.swift
Source/Filters/Video/YPVideoFiltersVC.swift
Source/Filters/Video/YPVideoView.swift
Source/Helpers/Extensions/PHCachingImageManager+Extensions.swift
Source/Helpers/YPAdjustableView.swift
Source/Models/YPLibrarySelection.swift
Source/Models/YPMediaItem.swift
Source/Pages/Gallery/YPAssetViewContainer.swift
Source/Pages/Gallery/YPAssetZoomableView.swift
Source/Pages/Gallery/YPGridView.swift
Source/Pages/Gallery/YPLibraryVC+CollectionView.swift
Source/Pages/Gallery/YPLibraryVC.swift
Source/Pages/Gallery/YPLibraryView.swift

This PR enables the auto-cropping feature in the `YPImagePicker` library when selecting multiple media assets, automatically cropping the selected resources based on the first selected media asset size. Additionally, it resets the resources to their original state upon deactivating the selection of multiple media assets.
- Added a new `fetchImage` method for fetching original size images in `PHCachingImageManager`.
- Removed the validation that only allowed auto-cropping to videos.
- Changed the logic for resizing and centering media assets in `YPAssetZoomableView`.
- Added new properties in `YPMediaItem` for getting scale, size and crop measures.
- Change the logic for resizing videos in `YPAdjustableView`.
- Added a new container view for video assets in `YPVideoView` and …

CC-550 Fix: When selecting media display auto cropping for additionally selected media assets

---

Source/Filters/Video/YPVideoView.swift
Source/Models/YPMediaItem.swift
Source/Pages/Gallery/LibraryMediaManager.swift
Source/Pages/Gallery/YPAssetViewContainer.swift
Source/Pages/Gallery/YPAssetZoomableView.swift
Source/Pages/Gallery/YPLibraryVC.swift
Source/YPPickerVC.swift

This PR contains four separate fixes:
- Fix asset centering when they're being pre-cropped -- now the cropping should default to center properly
- Stop "zooming" the play button on top of videos in some situations
- Apply rotation transforms correctly when processing "cropped" videos
- Fix stored crop position not being applied correctly when re-selecting media in multi-selection mode

fix: Fix issues in asset centering, auto-cropping and processing

---

Source/Pages/Gallery/LibraryMediaManager.swift
Source/Pages/Gallery/YPLibraryView.swift

Processing Slow Mo videos was previously failing. When these failures would occur the videos were processed with the passthrough preset. After some research it was found that the `AVMutableVideoComposition` was what was failing Slow Mo videos. This seemed to only trigger with Slow Mo videos that had audio disabled. Setting both `frameDuration` and `sourceTrackIDForFrameTiming` on the video composition allowed the videos to be processed without failure. This PR slightly changes the processing failed logic. Now processed videos will retry once more with Slow Mo video composition settings if processing fails the first time. However if the processing fails once more, then pass through is used as the final preset if all retry attempts fail as there might still be some edge cases that haven't …

Fix Slow Mo Processing

---

Example/ExampleViewController.swift
Source/Configuration/YPImagePickerConfiguration.swift
Source/Pages/Gallery/LibraryMediaManager.swift
Source/Pages/Gallery/YPAssetZoomableView.swift

This PR makes video processing configurable through a new `YPConfig` option. If this new config option is set by the client then processing will always occur and will prioritize using any provided `compressionTypeOverride`. If this config option is not set then normal processing rules apply.

Make Video Processing Configurable

---

Example/ExampleViewController.swift
Source/Configuration/YPImagePickerConfiguration.swift
Source/Filters/Photo/YPCoverImageView.swift
Source/Filters/Video/YPVideoFiltersVC.swift
Source/Filters/Video/YPVideoView.swift
Source/Helpers/YPAdjustableView.swift
Source/Pages/Gallery/LibraryMediaManager.swift
Source/Pages/Gallery/YPLibraryVC+PanGesture.swift
Source/Pages/Gallery/YPLibraryVC.swift
Source/Pages/Gallery/YPLibraryView.swift
Source/YPPickerVC.swift

This PR adds one new feature: ability to add a "footer" view underneath the asset preview on the library screen. 
Screenshot showing a simple "footer" view using the new configuration variable:
Additionally, the PR contains a few fixes and improvements: 
- Make some methods public to make subclassing easier
- Make the PanGestureHelper class less tightly tied into the library implementation, allowing its usage outside the library
- Fix the panning/scrolling logic in the library view to account for the album picker and the new custom footer view properly
- Also, update the logic of the panning to take the direction of the gesture into account, allowing "canceling" the gesture properly
- Allow processing videos without PHAssets (for cases where we only have a file on the disk)

feature: Add a way to add a custom "info view" to the library screen

---

Example/ExampleViewController.swift
Source/Configuration/YPImagePickerConfiguration.swift
Source/Pages/Gallery/YPAssetZoomableView.swift
Source/Pages/Gallery/YPLibraryView.swift

This PR adds a new configuration variable: `assetPreviewMaxHeight`, which allows setting the maximum height of the asset preview element. If the configuration variable is not set, it will default to square like it used to. If it _is_ set, the height will be limited to the given value. This will allow giving more space to the gallery grid in situations where we're using a tall `assetPreviewFooterView`. 
Screenshots showing previews in different aspect ratios with max height set to 280.0:
| Image orientation |     Square  | Landscape  | Portrait  |
| -- | -- | -- | -- |
| Screenshots |  <img src="https://github.com/rewardStyle/YPImagePicker/assets/122308456/2f69795a-5e8e-4916-9344-f9e4d57cacb4" width="300" />  | <img src="https://github.com/rewardStyle/YPImagePicker/assets/122308456/e44805e1 …

feat: Allow setting a max height for the asset preview

---

Source/Pages/Gallery/YPLibraryVC+CollectionView.swift

The problem was that we were calling `changeAsset` twice in rapid succession when a library cell was clicked, causing a problem with the preview if the first of the videos was slower to load than the second one.

fix: Do not call changeAsset twice when multi-selection is enabled

---

Source/Filters/Video/YPVideoFiltersVC.swift
Source/Pages/Gallery/LibraryMediaManager.swift
Source/Pages/Gallery/YPLibraryVC.swift

This PR adds supporting changes to be able to provide enough information so that the client app can send video processing information to DataDog. Each video that completes processing will provide the following information to the client:
- video height
- video width 
- video duration
- URL to where the video is
- a unique identifier (This can be either the `PHAsset localIdentifier or the remote URL in the case of IG uploads)
Changes were made to that both the single video flows + storytelling video flows can provide all the information the client needs to send through to DataDog.

Media Processing DataDog Observability Support

---

Source/Configuration/YPImagePickerConfiguration.swift
Source/Pages/Gallery/LibraryMediaManager.swift
Source/Pages/Gallery/YPLibraryVC.swift

[CC-1916](https://rewardstyle.atlassian.net/browse/CC-1916)
This PR adds a new `YPConfig` property: `shouldPreselectRecentsAlbum` which when true will display all media in a similar way the "Recents" album does in Photos. Essentially this takes all of the media from all smart albums and sorts them in inverse order so that the most recently added content appears on the top of the list instead of sorting the media by `creationDate` as the current implementation does. 
This functionality will be behind a new feature flag on the client that toggles this `YPConfig` property. 
A couple of details on the flows touched:
- The initial load of the image picker which shows all media sorted in inverse order
- Opening the albums picker and manually selecting "Recents" album persists this ordering.
- …

feat: [Creator] Add Ability To Fetch All Media And Sort Reversed [CC-1916]

---

Source/Filters/Photo/YPCoverImageView.swift
Source/Filters/Video/YPVideoView.swift

Just a small fix for some cases where the `preferredTransform` of a video causes negative values for the `size`. Now, we'll always use positive values for the video size when showing the video on the trim or cover selection screens.

fix: When using preferredTransform, use abs to prevent negative sizes

---

Package.swift
Source/Filters/Video/YPVideoFiltersVC.swift
YPImagePicker.xcodeproj/project.pbxproj
YPImagePicker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Supporting PR with changes for: 
- Communicating when a custom cover photo has been replaced by a video frame.
- Resets the thumb view border color when the thumb selector has been moved.

Custom Cover Photo UAT Low Priority Issue Fixes

---

Package.swift
Source/Filters/Video/YPVideoFiltersVC.swift
YPImagePicker.xcodeproj/project.pbxproj
YPImagePicker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Cover photo image generation was breaking after locking device or backgrounding the app. This only seemed to happen when testing on device and didn't occur on simulator. This PR sets up the generator again after coming back into the foreground.

fix: Fix Cover Photo Image Generation After Backgrounding

---

Source/Filters/Photo/YPPhotoFiltersVC.swift
Source/Filters/Video/YPVideoFiltersVC.swift
Source/SelectionsGallery/YPSelectionsGalleryVC.swift
Source/YPImagePicker.swift

Supporting PR that allows the client to know when a cover photo has been changed for single video when the UI only allows for the cover photo to be changed.

fix: Know When Cover Photo Is Changed When In Cover Only Selection Mode

---

Source/YPPickerVC.swift

Just changing a function to `open` to allow subclasses to override it.

fix: Allow overriding updateUI method in YPPickerVC

---

Source/Filters/Video/YPVideoFiltersVC.swift

Just a small bugfix: The cover thumb selector cover was incorrectly reset without parameters, which caused any custom colors to be overwritten to white.

fix: Reset thumb color to correct color, not white

---

Package.resolved
Package.swift

updated the stevia package to support iOS 26 and xcode 26

chore: update stevia package to 6.2.0 for iOS 26 support
